////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated. 
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace ajuUminho.webforms {
    
    
//    public partial class gestaoProcessos {
        
//        /// <summary>
//        /// Form control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.HtmlControls.HtmlForm Form;
        
//        /// <summary>
//        /// headerID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.header headerID;
        
//        /// <summary>
//        /// ListBoxProcessosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.ListBox ListBoxProcessosID;
        
//        /// <summary>
//        /// TabDadosGeraisID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button TabDadosGeraisID;
        
//        /// <summary>
//        /// TabContabilidadeID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button TabContabilidadeID;
        
//        /// <summary>
//        /// TabCredoresID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button TabCredoresID;
        
//        /// <summary>
//        /// TabAnexosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button TabAnexosID;
        
//        /// <summary>
//        /// TabRelatoriosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button TabRelatoriosID;
        
//        /// <summary>
//        /// TabEventosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button TabEventosID;
        
//        /// <summary>
//        /// TabServicosExternosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button TabServicosExternosID;
        
//        /// <summary>
//        /// MainViewID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.MultiView MainViewID;
        
//        /// <summary>
//        /// ViewDadosGeraisID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.View ViewDadosGeraisID;
        
//        /// <summary>
//        /// dadosGeraisID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.dadosGerais dadosGeraisID;
        
//        /// <summary>
//        /// ViewContabilidadeID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.View ViewContabilidadeID;
        
//        /// <summary>
//        /// contabilidadeID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.contabilidade contabilidadeID;
        
//        /// <summary>
//        /// ViewCredoresID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.View ViewCredoresID;
        
//        /// <summary>
//        /// credores control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.credores credores;
        
//        /// <summary>
//        /// ViewAnexosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.View ViewAnexosID;
        
//        /// <summary>
//        /// anexos control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.anexos anexos;
        
//        /// <summary>
//        /// ViewRelatoriosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.View ViewRelatoriosID;
        
//        /// <summary>
//        /// relatorios control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.relatorios relatorios;
        
//        /// <summary>
//        /// ViewEventosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.View ViewEventosID;
        
//        /// <summary>
//        /// eventosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.eventos eventosID;
        
//        /// <summary>
//        /// ViewServicosExternosID control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.View ViewServicosExternosID;
        
//        /// <summary>
//        /// servicosExternos control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ajuUminho.controls.servicosExternos servicosExternos;
//    }
//}
