//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajuUminho.webforms {
    
    
    public partial class InterfaceAdministracao {
        
        /// <summary>
        /// Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form;
        
        /// <summary>
        /// header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.utilizadores.i14TerminoDeSessao header;
        
        /// <summary>
        /// TabAdministradorUtilizadoresID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button TabAdministradorUtilizadoresID;
        
        /// <summary>
        /// TabAtribuirPerfilID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button TabAtribuirPerfilID;
        
        /// <summary>
        /// TabConfirmarPerfilID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button TabConfirmarPerfilID;
        
        /// <summary>
        /// MainViewID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView MainViewID;
        
        /// <summary>
        /// ViewAdministradorUtilizadoresID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View ViewAdministradorUtilizadoresID;
        
        /// <summary>
        /// administradorUtilizadoresID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.administracao.i3AdministradorUtilizadores administradorUtilizadoresID;
        
        /// <summary>
        /// ViewAtribuirPerfilID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View ViewAtribuirPerfilID;
        
        /// <summary>
        /// atribuirPerfilID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.administracao.i9AtribuirPerfil atribuirPerfilID;
        
        /// <summary>
        /// ViewConfirmarPerfilID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View ViewConfirmarPerfilID;
        
        /// <summary>
        /// confirmarPerfilID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.administracao.i10ConfirmarPerfil confirmarPerfilID;
    }
}
